name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["main"]

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  AR_REPO: ${{ vars.AR_REPO }}
  WEB_IMAGE: ${{ vars.WEB_IMAGE }}
  API_IMAGE: ${{ vars.API_IMAGE }}

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.DEPLOYER_SA }}
          audience: https://github.com/kdilts13/portfolio

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      # ===== API (Docker build/push) =====
      - name: Build & Push API image
        working-directory: api
        run: |
          IMAGE="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO/$API_IMAGE:latest"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy API to Cloud Run
        run: |
          gcloud run deploy api \
            --image="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO/$API_IMAGE:latest" \
            --region="$GCP_REGION" \
            --service-account="run-api@$GCP_PROJECT_ID.iam.gserviceaccount.com" \
            --allow-unauthenticated

      - name: Get API URL
        id: apiurl
        run: |
          API_URL=$(gcloud run services describe api --region="$GCP_REGION" --format="value(uri)")
          TESTVAR=$(gcloud run services describe api --region="$GCP_REGION")
          echo ">>> GCP_REGION:"
          echo ">>> $GCP_REGION"

          echo ">>> TESTVAR:"
          echo ">>> $TESTVAR"

          echo "API_URL=$API_URL" >> $GITHUB_OUTPUT

          echo ">>> API_URL:"
          echo ">>> $API_URL"

      # ===== WEB (Docker build with build-arg) =====
      - name: Build & Push WEB image (bakes NEXT_PUBLIC_API_BASE)
        working-directory: web
        run: |
          IMAGE="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO/$WEB_IMAGE:latest"
          docker build \
            --build-arg NEXT_PUBLIC_API_BASE="${{ steps.apiurl.outputs.API_URL }}" \
            -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy WEB to Cloud Run
        run: |
          gcloud run deploy web \
            --image="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO/$WEB_IMAGE:latest" \
            --region="$GCP_REGION" \
            --service-account="run-web@$GCP_PROJECT_ID.iam.gserviceaccount.com" \
            --allow-unauthenticated
